# Generated by Django 5.2.11 on 2026-02-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='accessory_sale',
            field=models.ForeignKey(blank=True, help_text='Optional related accessory sale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='core.accessorysale'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('PHONE_SELLER', 'Phone Seller'), ('ACCESSORY_SELLER', 'Accessory Seller')], max_length=50),
        ),
    ]
