# Generated by Django 5.2.11 on 2026-02-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_debt_accessory_sale_alter_branchuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='accessory_sale',
        ),
    ]
