# Generated by Django 5.2.11 on 2026-02-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_debt_accessory_sale'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accessorysale',
            index=models.Index(fields=['branch'], name='accessory_s_branch__d5440c_idx'),
        ),
        migrations.AddIndex(
            model_name='accessorysale',
            index=models.Index(fields=['sold_at'], name='accessory_s_sold_at_94cfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['branch'], name='debts_branch__00c3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['created_by'], name='debts_created_1efe5b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch'], name='expenses_branch__802c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by'], name='expenses_created_5ca70d_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['branch', 'is_sold'], name='phones_branch__8e79fd_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['sold_at'], name='phones_sold_at_a2835f_idx'),
        ),
    ]
