# Generated by Django 5.2.11 on 2026-02-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accessorysale_accessory_s_branch__d5440c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['debt'], name='debt_paymen_debt_id_3705b7_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['paid_by'], name='debt_paymen_paid_by_e697a0_idx'),
        ),
    ]
