# Generated by Django 5.2.11 on 2026-02-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debtpayment_debt_paymen_debt_id_3705b7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extraprofit',
            index=models.Index(fields=['branch'], name='extra_profi_branch__bc1856_idx'),
        ),
    ]
