# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_extraprofit_extra_profi_branch__bc1856_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="phonecapital",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="phonecapital",
            constraint=models.UniqueConstraint(
                fields=["branch", "month"],
                name="unique_phone_capital_month",
            ),
        ),
        migrations.AddIndex(
            model_name="phonecapital",
            index=models.Index(
                fields=["branch", "month"],
                name="phone_capital_branch_month_idx",
            ),
        ),
    ]
