# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_phonecapital_month_constraints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(fields=["remaining_amount"], name="debt_remainin_9c3a2b_idx"),
        ),
    ]
