# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_debt_remaining_amount_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch related to this journal entry.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journals",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="object_repr",
            field=models.CharField(
                blank=True,
                help_text="Human-readable object representation.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["branch"], name="journals_branch_id_90b9d0_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["user"], name="journals_user_id_4c2e26_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["model_name"], name="journals_model_n_799c13_idx"),
        ),
    ]
