# Generated by Django 5.2.11 on 2026-03-01 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journal_branch_object_repr_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-added_at'], 'verbose_name': 'Aksessuar', 'verbose_name_plural': 'Aksessuarlar'},
        ),
        migrations.AlterModelOptions(
            name='accessorycapital',
            options={'ordering': ['-month', '-added_at'], 'verbose_name': 'Aksessuar kapitali', 'verbose_name_plural': 'Aksessuar kapitallari'},
        ),
        migrations.AlterModelOptions(
            name='accessorycategory',
            options={'ordering': ['name'], 'verbose_name': 'Aksessuar kategoriyasi', 'verbose_name_plural': 'Aksessuar kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='accessorysale',
            options={'ordering': ['-sold_at', '-added_at'], 'verbose_name': 'Aksessuar savdosi', 'verbose_name_plural': 'Aksessuar savdolari'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-added_at'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='branchuser',
            options={'verbose_name': 'Filial roli', 'verbose_name_plural': 'Filial rollari'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-added_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-added_at'], 'verbose_name': 'Qarz', 'verbose_name_plural': 'Qarzlar'},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'ordering': ['-added_at'], 'verbose_name': 'Qarz to‘lovi', 'verbose_name_plural': 'Qarz to‘lovlari'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-added_at'], 'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='extraprofit',
            options={'ordering': ['-added_at'], 'verbose_name': 'Qo‘shimcha foyda', 'verbose_name_plural': 'Qo‘shimcha foydalar'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-added_at'], 'verbose_name': 'Jurnal', 'verbose_name_plural': 'Jurnallar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-added_at'], 'verbose_name': 'Telefon', 'verbose_name_plural': 'Telefonlar'},
        ),
        migrations.AlterModelOptions(
            name='phonecapital',
            options={'ordering': ['-month', '-added_at'], 'verbose_name': 'Telefon kapitali', 'verbose_name_plural': 'Telefon kapitallari'},
        ),
        migrations.AlterModelOptions(
            name='phonecategory',
            options={'ordering': ['name'], 'verbose_name': 'Telefon kategoriyasi', 'verbose_name_plural': 'Telefon kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-added_at'], 'verbose_name': 'Oylik', 'verbose_name_plural': 'Oyliklar'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-added_at'], 'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-added_at'], 'verbose_name': 'Obuna to‘lovi', 'verbose_name_plural': 'Obuna to‘lovlari'},
        ),
        migrations.RenameIndex(
            model_name='debt',
            new_name='debts_remaini_2f7138_idx',
            old_name='debt_remainin_9c3a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='journals_branch__3d4a08_idx',
            old_name='journals_branch_id_90b9d0_idx',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='journals_user_id_786370_idx',
            old_name='journals_user_id_4c2e26_idx',
        ),
        migrations.RenameIndex(
            model_name='journal',
            new_name='journals_model_n_98f307_idx',
            old_name='journals_model_n_799c13_idx',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='added_by',
            field=models.ForeignKey(help_text='Aksessuarni qo‘shgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='added_accessories', to=settings.AUTH_USER_MODEL, verbose_name='Qo‘shgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='branch',
            field=models.ForeignKey(help_text='Aksessuar tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(help_text='Aksessuar kategoriyasi.', on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='core.accessorycategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, help_text='Aksessuar rasmi.', null=True, upload_to='accessories/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Aksessuar faollik holati.', verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(help_text='Aksessuar mahsuloti nomi.', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Hozirgi qoldiq soni.', verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Bir dona tannarx.', max_digits=14, verbose_name='Birlik tannarxi'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='branch',
            field=models.ForeignKey(help_text='Kapital tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='accessory_capitals', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aksessuar kapitalining hozirgi balansi.', max_digits=14, verbose_name='Hozirgi balans'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ushbu oy uchun aksessuar kapitaliga tikilgan pul.', max_digits=14, verbose_name='Tikilgan pul'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='month',
            field=models.DateField(help_text='Kapital oyi (oyning birinchi kuni).', verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='accessorycapital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='description',
            field=models.TextField(blank=True, help_text='Ixtiyoriy kategoriya tavsifi.', null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='name',
            field=models.CharField(help_text='Aksessuar kategoriyasi nomi.', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='accessorycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='accessory',
            field=models.ForeignKey(help_text='Sotilayotgan aksessuar.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.accessory', verbose_name='Aksessuar'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='branch',
            field=models.ForeignKey(help_text='Savdo bo‘lib o‘tgan filial.', on_delete=django.db.models.deletion.PROTECT, related_name='accessory_sales', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='profit',
            field=models.DecimalField(decimal_places=2, help_text='Foyda = jami sotuv − jami tannarx.', max_digits=14, verbose_name='Foyda'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Sotilgan soni.', verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='sold_at',
            field=models.DateTimeField(help_text='Savdo sanasi/vaqti.', verbose_name='Sotilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='sold_by',
            field=models.ForeignKey(help_text='Aksessuarni sotgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='accessory_sales', to=settings.AUTH_USER_MODEL, verbose_name='Sotgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Jami tannarx = soni × birlik tannarx.', max_digits=14, verbose_name='Jami tannarx'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Sotuvchi kiritgan jami sotuv narxi.', max_digits=14, verbose_name='Jami sotuv narxi'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Savdo paytidagi birlik tannarx (snapshot).', max_digits=14, verbose_name='Birlik tannarxi'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, help_text='Filial manzili.', max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Filial faollik holati.', verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Filial nomi.', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='owner',
            field=models.ForeignKey(help_text='Filial egasi.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_branches', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Egasi'), ('PHONE_SELLER', 'Telefon sotuvchisi'), ('ACCESSORY_SELLER', 'Aksessuar sotuvchisi')], max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_roles', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_cashier',
            field=models.BooleanField(default=False, help_text='Ushbu foydalanuvchi tizim kassiri.', verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP foydalanuvchilar bepul va bloklanmaydi.', verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Ixtiyoriy telefon raqami.', max_length=32, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Qarz summasi.', max_digits=14, verbose_name='Qarz summasi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='branch',
            field=models.ForeignKey(help_text='Qarz tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created_by',
            field=models.ForeignKey(help_text='Qarzni yaratgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='created_debts', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='direction',
            field=models.CharField(choices=[('WE_GAVE', 'Biz berdik'), ('WE_TOOK', 'Biz oldik')], help_text='Qarz yo‘nalishi.', max_length=16, verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='note',
            field=models.TextField(blank=True, help_text='Ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='phone',
            field=models.ForeignKey(blank=True, help_text='Ixtiyoriy bog‘langan telefon.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='core.phone', verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, help_text='To‘lanmagan qoldiq summa.', max_digits=14, verbose_name='Qoldiq'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='To‘lov summasi.', max_digits=14, verbose_name='To‘lov summasi'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='debt',
            field=models.ForeignKey(help_text='To‘lanayotgan qarz.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.debt', verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='note',
            field=models.TextField(blank=True, help_text='Ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='paid_by',
            field=models.ForeignKey(help_text='To‘lovni kiritgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='debt_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Xarajat summasi.', max_digits=14, verbose_name='Xarajat summasi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(help_text='Xarajat tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(help_text='Xarajatni yaratgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, help_text='Ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('SHOP_EXPENSE', 'Do‘kon xarajati'), ('EMPLOYEE_EXPENSE', 'Xodim xarajati')], help_text='Xarajat turi.', max_length=32, verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Qo‘shimcha foyda summasi.', max_digits=14, verbose_name='Foyda summasi'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='branch',
            field=models.ForeignKey(help_text='Qo‘shimcha foyda olgan filial.', on_delete=django.db.models.deletion.PROTECT, related_name='extra_profits', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='created_by',
            field=models.ForeignKey(help_text='Qo‘shimcha foydani kiritgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='created_extra_profits', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='note',
            field=models.TextField(blank=True, help_text='Foyda manbasi bo‘yicha ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='extraprofit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Yangilash'), ('DELETE', 'O‘chirish')], help_text='Amal turi.', max_length=16, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Jurnal yozuvi tegishli filial.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='model_name',
            field=models.CharField(help_text='O‘zgartirilgan model.', max_length=255, verbose_name='Model nomi'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='new_data',
            field=models.JSONField(blank=True, help_text='Yangi ma’lumotlar snapshoti.', null=True, verbose_name='Yangi ma’lumotlar'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='object_id',
            field=models.IntegerField(help_text='O‘zgartirilgan obyekt ID si.', verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='object_repr',
            field=models.CharField(blank=True, help_text='Obyektning o‘qiladigan ko‘rinishi.', max_length=255, null=True, verbose_name='Obyekt ko‘rinishi'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='old_data',
            field=models.JSONField(blank=True, help_text='Oldingi ma’lumotlar snapshoti.', null=True, verbose_name='Oldingi ma’lumotlar'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(help_text='Amalni bajargan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='added_by',
            field=models.ForeignKey(help_text='Telefonni qo‘shgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='added_phones', to=settings.AUTH_USER_MODEL, verbose_name='Qo‘shgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='branch',
            field=models.ForeignKey(help_text='Telefon tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(help_text='Telefon kategoriyasi.', on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='core.phonecategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, help_text='Telefon rangi.', max_length=64, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Telefon xarid tannarxi.', max_digits=14, verbose_name='Tannarx'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='from_by',
            field=models.CharField(help_text='Telefon qayerdan xarid qilingan.', max_length=255, verbose_name='Qayerdan olingan'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(help_text='Telefon IMEI raqami.', max_length=64, unique=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Telefon sotilganligi.', verbose_name='Sotilgan'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(help_text='Telefon modeli nomi.', max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Telefon sotuv narxi.', max_digits=14, null=True, verbose_name='Sotuv narxi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sold_at',
            field=models.DateTimeField(blank=True, help_text='Telefon sotilgan sana/vaqti.', null=True, verbose_name='Sotilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sold_by',
            field=models.ForeignKey(blank=True, help_text='Telefonni sotgan foydalanuvchi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_phones', to=settings.AUTH_USER_MODEL, verbose_name='Sotgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1024', '1 TB'), ('2048', '2 TB')], help_text='Telefon xotirasi (masalan: 128GB).', max_length=64, verbose_name='Xotira'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='branch',
            field=models.ForeignKey(help_text='Kapital tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='phone_capitals', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Telefon kapitalining hozirgi balansi.', max_digits=14, verbose_name='Hozirgi balans'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ushbu oy uchun telefon kapitaliga tikilgan pul.', max_digits=14, verbose_name='Tikilgan pul'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='month',
            field=models.DateField(help_text='Kapital oyi (oyning birinchi kuni).', verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='phonecapital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Ixtiyoriy kategoriya tavsifi.', null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='name',
            field=models.CharField(help_text='Telefon kategoriyasi nomi.', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Oylik summasi.', max_digits=14, verbose_name='Oylik summasi'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='branch',
            field=models.ForeignKey(help_text='Filial.', on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='core.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(help_text='Oylikni yaratgan egasi.', on_delete=django.db.models.deletion.PROTECT, related_name='created_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(help_text='Oylik oluvchi xodim.', on_delete=django.db.models.deletion.PROTECT, related_name='received_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='note',
            field=models.TextField(blank=True, help_text='Ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(help_text='Obuna tugash sanasi/vaqti.', verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_end_date',
            field=models.DateTimeField(help_text='Imtiyoz muddati tugash sanasi/vaqti.', verbose_name='Imtiyoz muddati tugashi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('MONTHLY', 'Oylik'), ('YEARLY', 'Yillik'), ('VIP', 'VIP')], help_text='Obuna reja turi.', max_length=16, verbose_name='Reja turi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(help_text='Obuna boshlanish sanasi/vaqti.', verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('GRACE', 'Imtiyoz muddati'), ('BLOCKED', 'Bloklangan')], help_text='Obuna holati.', max_length=16, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(help_text='Obuna foydalanuvchisi.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='added_by',
            field=models.ForeignKey(help_text='To‘lovni kim kiritgan (kassir/egasi/admin).', on_delete=django.db.models.deletion.PROTECT, related_name='added_subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='To‘lov summasi.', max_digits=14, verbose_name='To‘lov summasi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='note',
            field=models.TextField(blank=True, help_text='Ixtiyoriy izoh.', null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='To‘lov sanasi/vaqti.', verbose_name='To‘lov vaqti'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Oylik'), ('YEARLY', 'Yillik')], help_text='To‘lov davr turi.', max_length=16, verbose_name='Davr turi'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(help_text='Bog‘langan obuna.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.subscription', verbose_name='Obuna'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user',
            field=models.ForeignKey(help_text='Obuna uchun to‘lov qilgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
