# Generated by Django 5.2.11 on 2026-03-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_accessory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='phone',
        ),
        migrations.AddField(
            model_name='debt',
            name='f_name',
            field=models.CharField(blank=True, help_text='Familya Ism Sharif', max_length=255, null=True, verbose_name='FIO'),
        ),
    ]
