# Generated by Django 5.2.11 on 2026-03-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_debt_phone_debt_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='f_name',
        ),
        migrations.AddField(
            model_name='debt',
            name='phone',
            field=models.ForeignKey(blank=True, help_text='Ixtiyoriy bog‘langan telefon.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='core.phone', verbose_name='Telefon'),
        ),
    ]
