# Generated by Django 5.2.11 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_debt_f_name_debt_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="f_name",
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                help_text="Qarz kim bilan bog‘liq (ism familiya)",
            ),
        ),
    ]
