# Generated by Django 5.2.11 on 2026-03-04 00:00

from django.db import migrations


BATCH_SIZE = 500


def populate_debt_f_name(apps, schema_editor):
    Debt = apps.get_model("core", "Debt")
    db_alias = schema_editor.connection.alias

    qs = (
        Debt.objects.using(db_alias)
        .select_related("phone")
        .filter(phone__isnull=False)
    )

    batch = []
    for debt in qs.iterator():
        if getattr(debt, "f_name", None):
            continue
        phone = getattr(debt, "phone", None)
        if not phone:
            continue
        phone_name = getattr(phone, "name", None)
        if phone_name:
            debt.f_name = phone_name
        else:
            debt.f_name = str(phone)
        batch.append(debt)
        if len(batch) >= BATCH_SIZE:
            Debt.objects.using(db_alias).bulk_update(batch, ["f_name"])
            batch = []

    if batch:
        Debt.objects.using(db_alias).bulk_update(batch, ["f_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_debt_f_name"),
    ]

    operations = [
        migrations.RunPython(populate_debt_f_name, migrations.RunPython.noop),
    ]
