# Generated by Django 5.2.11 on 2026-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_populate_debt_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(help_text='Telefon IMEI raqami.', max_length=64, verbose_name='IMEI'),
        ),
    ]
