# Generated by Django 5.2.11 on 2026-03-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessorycapital',
            new_name='acc_cap_branch_month_idx',
            old_name='accessory_capital_branch_month_idx',
        ),
        migrations.RenameIndex(
            model_name='accessorycapital',
            new_name='acc_cap_is_del_idx',
            old_name='accessory_capital_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='accessorycategory',
            new_name='acc_cat_is_del_idx',
            old_name='accessory_category_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='extraprofit',
            new_name='extra_profit_branch_add_idx',
            old_name='extra_profit_branch_added_at_idx',
        ),
    ]
