# Generated by Django 5.2.11 on 2026-03-16 00:00

from decimal import Decimal

from django.db import migrations, models


def populate_remaining_balance(apps, schema_editor):
    Debt = apps.get_model("core", "Debt")
    DebtPayment = apps.get_model("core", "DebtPayment")

    debt_amounts = dict(
        Debt._base_manager.values_list("id", "amount")
    )
    debt_ids = (
        DebtPayment._base_manager.order_by()
        .values_list("debt_id", flat=True)
        .distinct()
    )

    for debt_id in debt_ids:
        remaining_balance = debt_amounts.get(debt_id) or Decimal("0")
        payments = list(
            DebtPayment._base_manager.filter(debt_id=debt_id).order_by("added_at", "id")
        )

        for payment in payments:
            remaining_balance = remaining_balance - (payment.amount or Decimal("0"))
            payment.remaining_balance = remaining_balance

        if payments:
            DebtPayment._base_manager.bulk_update(payments, ["remaining_balance"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_accessory_capital_branch_month_idx_acc_cap_branch_month_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtpayment",
            name="remaining_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="To‘lovdan keyingi qoldiq summa.",
                max_digits=14,
                verbose_name="Qoldiq",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_remaining_balance,
            migrations.RunPython.noop,
        ),
    ]
