# Generated by Django 5.2.11 on 2026-03-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_debtpayment_remaining_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthClosingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Yaratilgan sana/vaqt.",
                        verbose_name="Yaratilgan vaqt",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Yangilangan sana/vaqt.",
                        verbose_name="Yangilangan vaqt",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Yumshoq o‘chirish holati.",
                        verbose_name="O‘chirilgan",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Yopilgan oy (oyning birinchi kuni).",
                        verbose_name="Oy",
                    ),
                ),
                (
                    "phones_closed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Oy yopilishida yopilgan telefonlar soni.",
                        verbose_name="Yopilgan telefonlar",
                    ),
                ),
                (
                    "phones_recreated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Keyingi oy uchun qayta yaratilgan telefonlar soni.",
                        verbose_name="Qayta yaratilgan telefonlar",
                    ),
                ),
                (
                    "accessories_processed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Oy yopilishida qayta hisoblangan aksessuarlar soni.",
                        verbose_name="Qayta hisoblangan aksessuarlar",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Oy yopilgan filial.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="month_closings",
                        to="core.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oy yopilishi",
                "verbose_name_plural": "Oy yopilishlari",
                "db_table": "month_closing_records",
                "ordering": ["-month", "-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monthclosingrecord",
            index=models.Index(
                fields=["branch", "month"],
                name="month_close_branch_month_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthclosingrecord",
            index=models.Index(
                fields=["is_deleted"],
                name="month_close_is_deleted_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthclosingrecord",
            constraint=models.UniqueConstraint(
                fields=("branch", "month"),
                name="unique_branch_month_closing",
            ),
        ),
    ]
