# Generated by Django 5.2.11 on 2026-03-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_debtpayment_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtpayment',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='To‘lovdan keyingi qoldiq summa.', max_digits=14, verbose_name='Qoldiq'),
        ),
    ]
