# Generated by Django 5.2.11 on 2026-03-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_debtpayment_remaining_balance"),
        ("core", "0019_monthclosingrecord"),
    ]

    operations = []
