# Generated by Django 5.2.11 on 2026-03-25 09:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_account_status(apps, schema_editor):
    CustomUser = apps.get_model("core", "CustomUser")
    CustomUser.objects.filter(is_vip=True).update(
        account_status="vip",
        grace_start_date=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20260316_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Faol'), ('grace', 'Imtiyoz muddati'), ('blocked', 'Bloklangan'), ('vip', 'Imtiyozli')], default='active', help_text='Billing bo‘yicha joriy hisob holati.', max_length=16, verbose_name='Hisob holati'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Foydalanuvchining joriy balansi.', max_digits=14, verbose_name='Balans'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('3300.00'), help_text='Har kuni yechiladigan summa.', max_digits=14, verbose_name='Kunlik to‘lov'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grace_start_date',
            field=models.DateField(blank=True, help_text='Balans manfiy bo‘lganda boshlangan sana.', null=True, verbose_name='Imtiyoz boshlanish sanasi'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Qo‘shilgan to‘lov summasi.', max_digits=14, verbose_name='Summa')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('cash', 'Naqd')], help_text='To‘lov kanali yoki usuli.', max_length=16, verbose_name='To‘lov turi')),
                ('added_by', models.ForeignKey(help_text='To‘lovni kiritgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='added_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim qo‘shgan')),
                ('user', models.ForeignKey(help_text='To‘lov qaysi foydalanuvchi uchun qo‘shilgan.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
                'db_table': 'payments',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user'], name='payment_user_idx'), models.Index(fields=['payment_type'], name='payment_type_idx'), models.Index(fields=['added_by'], name='payment_added_by_idx'), models.Index(fields=['added_at'], name='payment_added_at_idx'), models.Index(fields=['is_deleted'], name='payment_is_deleted_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('type', models.CharField(choices=[('daily_charge', 'Kunlik yechim'), ('payment', 'To‘lov'), ('manual_adjustment', 'Qo‘lda o‘zgartirish')], help_text='Tranzaksiya turi.', max_length=32, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tranzaksiya summasi.', max_digits=14, verbose_name='Summa')),
                ('charge_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Amal bajarilgan sana va vaqt.', verbose_name='Sana')),
                ('charge_day', models.DateField(blank=True, editable=False, help_text='Kunlik yechimlar uchun texnik sana maydoni.', null=True, verbose_name='Hisoblangan kun')),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Amaldan oldingi balans.', max_digits=14, verbose_name='Oldingi balans')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Amaldan keyingi balans.', max_digits=14, verbose_name='Keyingi balans')),
                ('user', models.ForeignKey(help_text='Tranzaksiya tegishli foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya jurnali',
                'verbose_name_plural': 'Tranzaksiya jurnallari',
                'db_table': 'transaction_logs',
                'ordering': ['-charge_date', '-id'],
                'indexes': [models.Index(fields=['user'], name='txnlog_user_idx'), models.Index(fields=['type'], name='txnlog_type_idx'), models.Index(fields=['charge_date'], name='txnlog_charge_date_idx'), models.Index(fields=['charge_day'], name='txnlog_charge_day_idx'), models.Index(fields=['added_at'], name='txnlog_added_at_idx'), models.Index(fields=['is_deleted'], name='txnlog_is_deleted_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('type', 'daily_charge')), fields=('user', 'charge_day', 'type'), name='uniq_daily_charge_per_user_day')],
            },
        ),
        migrations.RunPython(backfill_account_status, migrations.RunPython.noop),
    ]
