# Generated by Codex on 2026-03-30

from django.db import migrations, models


def backfill_month_closing_timestamps(apps, schema_editor):
    MonthClosingRecord = apps.get_model("core", "MonthClosingRecord")

    for record in MonthClosingRecord.objects.filter(started_at__isnull=True).iterator():
        MonthClosingRecord.objects.filter(pk=record.pk).update(
            started_at=record.added_at,
            completed_at=record.updated_at,
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_customuser_account_status_customuser_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthclosingrecord",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Oy yopilish jarayoni yakunlangan vaqt.",
                null=True,
                verbose_name="Yakunlangan vaqt",
            ),
        ),
        migrations.AddField(
            model_name="monthclosingrecord",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Oy yopilish jarayoni boshlangan vaqt.",
                null=True,
                verbose_name="Boshlangan vaqt",
            ),
        ),
        migrations.AddField(
            model_name="monthclosingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Boshlangan"),
                    ("completed", "Yakunlangan"),
                    ("failed", "Muvaffaqiyatsiz"),
                ],
                default="completed",
                help_text="Oy yopilish jarayonining holati.",
                max_length=16,
                verbose_name="Holat",
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="for_month_close",
            field=models.BooleanField(
                default=False,
                help_text="Telefon oy yopilishida keyingi oyga ko‘chirilganligini bildiradi.",
                verbose_name="Oy yopilishi orqali ko‘chirilgan",
            ),
        ),
        migrations.RunPython(
            backfill_month_closing_timestamps,
            reverse_code=noop_reverse,
        ),
    ]
