# Generated by Django 5.2.11 on 2026-04-08 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_debt_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Snapshot oyi (oyning birinchi kuni).', verbose_name='Oy')),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Tanlangan oy oxiridagi qoldiq summa.', max_digits=14, verbose_name='Qoldiq')),
                ('total_paid_until_month', models.DecimalField(decimal_places=2, help_text='Tanlangan oy oxirigacha jami to‘langan summa.', max_digits=14, verbose_name='Shu oygacha to‘langan')),
                ('direction', models.CharField(choices=[('WE_GAVE', 'Biz berdik'), ('WE_TOOK', 'Biz oldik')], help_text='Qarz yo‘nalishi snapshotdagi holatda.', max_length=16, verbose_name='Yo‘nalish')),
                ('f_name', models.CharField(blank=True, help_text='Qarz kim bilan bog‘liq (ism familiya).', max_length=255, null=True)),
                ('note', models.TextField(blank=True, help_text='Snapshotdagi izoh nusxasi.', null=True, verbose_name='Izoh')),
                ('original_created_at', models.DateTimeField(help_text='Asl qarz yaratilgan vaqt.', verbose_name='Asl yaratilgan vaqt')),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, help_text='Snapshot yozuvi yaratilgan vaqt.', verbose_name='Snapshot yaratilgan vaqt')),
                ('branch', models.ForeignKey(help_text='Snapshot tegishli filial.', on_delete=django.db.models.deletion.PROTECT, related_name='debt_monthly_snapshots', to='core.branch', verbose_name='Filial')),
                ('created_by', models.ForeignKey(help_text='Qarzni kiritgan foydalanuvchi nusxasi.', on_delete=django.db.models.deletion.PROTECT, related_name='debt_monthly_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan')),
                ('debt', models.ForeignKey(help_text='Snapshot tegishli qarz.', on_delete=django.db.models.deletion.PROTECT, related_name='monthly_snapshots', to='core.debt', verbose_name='Qarz')),
            ],
            options={
                'verbose_name': 'Qarz oylik snapshoti',
                'verbose_name_plural': 'Qarz oylik snapshotlari',
                'db_table': 'debt_monthly_snapshots',
                'ordering': ['-month', '-snapshot_created_at', '-id'],
                'indexes': [models.Index(fields=['month'], name='debt_snap_month_idx'), models.Index(fields=['branch', 'month'], name='debt_snap_branch_month_idx'), models.Index(fields=['created_by', 'month'], name='debt_snap_creator_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('debt', 'month'), name='unique_debt_month_snapshot')],
            },
        ),
    ]
