# Generated by Codex on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_debtmonthlysnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessorycapital",
            name="debt_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Snapshot asosida qo‘llangan qarz tuzatmasi.",
                max_digits=14,
                verbose_name="Qarz tuzatmasi",
            ),
        ),
        migrations.AddField(
            model_name="monthclosingrecord",
            name="debt_adjustment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Oy yopilishida capitalga qo‘llangan jami qarz tuzatmasi.",
                max_digits=14,
                verbose_name="Qarz tuzatmasi summasi",
            ),
        ),
        migrations.AddField(
            model_name="monthclosingrecord",
            name="debt_adjustment_applied",
            field=models.BooleanField(
                default=False,
                help_text="Snapshotdan capitalga qarz tuzatmasi qo‘llanganligini bildiradi.",
                verbose_name="Qarz tuzatmasi qo‘llangan",
            ),
        ),
        migrations.AddField(
            model_name="phonecapital",
            name="debt_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Snapshot asosida qo‘llangan qarz tuzatmasi.",
                max_digits=14,
                verbose_name="Qarz tuzatmasi",
            ),
        ),
    ]
