# Generated by Django 5.2.11 on 2026-04-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_capital_debt_adjustment_and_monthclosing_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Dashboard snapshot oyi (oyning birinchi kuni).', verbose_name='Oy')),
                ('dashboard_data', models.JSONField(default=dict, help_text='Filial dashboardining saqlangan holati.', verbose_name='Dashboard ma’lumotlari')),
                ('phone_data', models.JSONField(blank=True, default=dict, help_text='Telefon dashboardining saqlangan holati.', verbose_name='Telefon dashboard ma’lumotlari')),
                ('accessory_data', models.JSONField(blank=True, default=dict, help_text='Aksessuar dashboardining saqlangan holati.', verbose_name='Aksessuar dashboard ma’lumotlari')),
                ('debt_data', models.JSONField(blank=True, default=dict, help_text='Qarz bo‘limining saqlangan holati.', verbose_name='Qarz ma’lumotlari')),
                ('expense_data', models.JSONField(blank=True, default=dict, help_text='Xarajat bo‘limining saqlangan holati.', verbose_name='Xarajat ma’lumotlari')),
                ('salary_data', models.JSONField(blank=True, default=dict, help_text='Maosh bo‘limining saqlangan holati.', verbose_name='Maosh ma’lumotlari')),
                ('capital_data', models.JSONField(blank=True, default=dict, help_text='Kapital bo‘limining saqlangan holati.', verbose_name='Kapital ma’lumotlari')),
                ('is_locked', models.BooleanField(default=True, help_text='Snapshot oyi muzlatilganligini bildiradi.', verbose_name='Qulflangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Snapshot yaratilgan vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Snapshot yangilangan vaqt.', verbose_name='Yangilangan vaqt')),
                ('branch', models.ForeignKey(help_text='Snapshot tegishli filial.', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshots', to='core.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Dashboard snapshot',
                'verbose_name_plural': 'Dashboard snapshotlar',
                'db_table': 'dashboard_snapshots',
                'ordering': ['-month', '-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'month'], name='dash_snap_branch_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'month'), name='unique_branch_month_dashboard_snapshot')],
            },
        ),
    ]
