# Generated by Django 5.2.11 on 2026-04-27 13:30

from django.db import migrations, models


def populate_expense_capital_type(apps, schema_editor):
    Expense = apps.get_model("core", "Expense")
    BranchUser = apps.get_model("core", "BranchUser")

    role_map = {}
    for user_id, branch_id, role in BranchUser._base_manager.filter(is_deleted=False).values_list(
        "user_id",
        "branch_id",
        "role",
    ):
        role_map.setdefault((user_id, branch_id), set()).add(role)

    for expense in Expense._base_manager.filter(capital_type__isnull=True).only(
        "id",
        "created_by_id",
        "branch_id",
        "type",
    ):
        roles = role_map.get((expense.created_by_id, expense.branch_id), set())
        capital_type = None

        if "PHONE_SELLER" in roles:
            capital_type = "phone"
        elif "ACCESSORY_SELLER" in roles:
            capital_type = "accessory"
        elif expense.type == "SHOP_EXPENSE":
            capital_type = "phone"
        elif expense.type == "EMPLOYEE_EXPENSE":
            capital_type = "accessory"

        if capital_type:
            Expense._base_manager.filter(pk=expense.pk).update(capital_type=capital_type)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_dashboardsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="capital_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Telefon kapitali"),
                    ("accessory", "Aksessuar kapitali"),
                ],
                help_text="Xarajat ta’sir qilgan kapital turi.",
                max_length=16,
                null=True,
                verbose_name="Kapital turi",
            ),
        ),
        migrations.RunPython(populate_expense_capital_type, migrations.RunPython.noop),
    ]
