# Generated by Django 5.2.11 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_expense_capital_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile_pin_hash",
            field=models.CharField(
                blank=True,
                help_text="Mobil ilova uchun 4 xonali PIN xeshi.",
                max_length=128,
                null=True,
                verbose_name="Mobil PIN xeshi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                help_text="Mobil ilova uchun tanlangan tema.",
                max_length=16,
                verbose_name="Tema",
            ),
        ),
    ]
