# Generated by Django 5.2.11 on 2026-04-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customuser_mobile_pin_hash_customuser_theme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_month_closed',
            field=models.BooleanField(default=False, help_text="Aksessuar oy yopilishida yopilgan va keyingi oyga ko'chirilgan.", verbose_name='Oy yopilgan'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='month_closed_at',
            field=models.DateTimeField(blank=True, help_text='Aksessuar oy yopilishida yopilgan vaqt.', null=True, verbose_name='Oy yopilgan vaqt'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='rolled_over_from',
            field=models.ForeignKey(blank=True, help_text="Bu aksessuar qaysi eski aksessuurdan ko'chirilganligi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollovers', to='core.accessory', verbose_name="Ko'chirilgan manba"),
        ),
        migrations.AddField(
            model_name='monthclosingrecord',
            name='accessories_recreated',
            field=models.PositiveIntegerField(default=0, help_text='Keyingi oy uchun qayta yaratilgan aksessuar qatorlari soni.', verbose_name='Qayta yaratilgan aksessuarlar'),
        ),
        migrations.AddField(
            model_name='monthclosingrecord',
            name='accessory_rollover_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Keyingi oy AccessoryCapital.invested_amount’ga qo’shilgan jami summa.', max_digits=14, verbose_name='Aksessuar rollover summasi'),
        ),
        migrations.AddField(
            model_name='monthclosingrecord',
            name='accessory_rollover_applied',
            field=models.BooleanField(default=False, help_text='Aksessuar rollover kapital ta’siri qo’llanganligini bildiradi.', verbose_name='Aksessuar rollover qo’llangan'),
        ),
        migrations.AddField(
            model_name='monthclosingrecord',
            name='phone_rollover_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Keyingi oy PhoneCapital.current_balance’dan ayirilgan jami summa.', max_digits=14, verbose_name='Telefon rollover summasi'),
        ),
        migrations.AddField(
            model_name='monthclosingrecord',
            name='phone_rollover_applied',
            field=models.BooleanField(default=False, help_text='Telefon rollover kapital ta’siri qo’llanganligini bildiradi.', verbose_name='Telefon rollover qo’llangan'),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_month_closed',
            field=models.BooleanField(default=False, help_text='Telefon oy yopilishida yopilgan va keyingi oyga ko’chirilgan.', verbose_name='Oy yopilgan'),
        ),
        migrations.AddField(
            model_name='phone',
            name='month_closed_at',
            field=models.DateTimeField(blank=True, help_text='Telefon oy yopilishida yopilgan vaqt.', null=True, verbose_name='Oy yopilgan vaqt'),
        ),
        migrations.AddField(
            model_name='phone',
            name='rolled_over_from',
            field=models.ForeignKey(blank=True, help_text='Bu telefon qaysi eski telefondan ko’chirilganligi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollovers', to='core.phone', verbose_name='Ko’chirilgan manba'),
        ),
        migrations.AlterField(
            model_name='monthclosingrecord',
            name='debt_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Oy yopilishida capitalga qo’llangan jami qarz tuzatmasi.', max_digits=14, verbose_name='Qarz tuzatmasi summasi'),
        ),
        migrations.AlterField(
            model_name='monthclosingrecord',
            name='debt_adjustment_applied',
            field=models.BooleanField(default=False, help_text='Snapshotdan capitalga qarz tuzatmasi qo’llanganligini bildiradi.', verbose_name='Qarz tuzatmasi qo’llangan'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='for_month_close',
            field=models.BooleanField(default=False, help_text='Telefon oy yopilishida keyingi oyga ko’chirilganligini bildiradi.', verbose_name='Oy yopilishi orqali ko’chirilgan'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['branch', 'is_month_closed'], name='acc_branch_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['branch', 'is_month_closed'], name='phone_branch_month_closed_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_month_closed', False)), fields=('branch', 'name', 'unit_cost'), name='unique_active_accessory_branch_name_cost'),
        ),
    ]
