# Generated by Django 5.2.11 on 2026-05-11 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_inventory_rollover_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('request_type', models.CharField(choices=[('CONTACT', 'Murojaat'), ('ACCOUNT_DELETE', 'Account o‘chirish'), ('TECHNICAL', 'Texnik masala')], max_length=32, verbose_name='Murojaat turi')),
                ('source', models.CharField(choices=[('MOBILE_APP', 'Mobile app'), ('LANDING_SITE', 'Landing site'), ('TELEGRAM_BOT', 'Telegram bot'), ('ADMIN', 'Admin')], default='MOBILE_APP', max_length=32, verbose_name='Manba')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='To‘liq ism')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('IN_PROGRESS', 'Jarayonda'), ('RESOLVED', 'Hal qilindi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=32, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo‘shimcha ma'lumot")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'db_table': 'support_requests',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['request_type'], name='support_req_type_idx'), models.Index(fields=['source'], name='support_req_source_idx'), models.Index(fields=['status'], name='support_req_status_idx'), models.Index(fields=['user'], name='support_req_user_idx'), models.Index(fields=['phone'], name='support_req_phone_idx'), models.Index(fields=['added_at'], name='support_req_added_at_idx')],
            },
        ),
    ]
