# Generated by Django 5.2.11 on 2026-05-11 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_support_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('sender_type', models.CharField(choices=[('USER', 'Foydalanuvchi'), ('ADMIN', 'Admin'), ('SYSTEM', 'System'), ('EXTERNAL', 'Tashqi manba')], max_length=16, verbose_name='Yuboruvchi turi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo‘shimcha ma'lumot")),
            ],
            options={
                'verbose_name': 'Murojaat xabari',
                'verbose_name_plural': 'Murojaat xabarlari',
                'db_table': 'support_request_messages',
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admin o‘qigan vaqt'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='last_admin_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi admin javobi vaqti'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi foydalanuvchi xabari vaqti'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='user_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Foydalanuvchi o‘qigan vaqt'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['last_message_at'], name='support_req_last_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['user_read_at'], name='support_req_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['admin_read_at'], name='support_req_admin_read_idx'),
        ),
        migrations.AddField(
            model_name='supportrequestmessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportrequest', verbose_name='Murojaat'),
        ),
        migrations.AddField(
            model_name='supportrequestmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AddIndex(
            model_name='supportrequestmessage',
            index=models.Index(fields=['request'], name='support_msg_request_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestmessage',
            index=models.Index(fields=['sender_type'], name='support_msg_sender_type_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestmessage',
            index=models.Index(fields=['added_at'], name='support_msg_added_at_idx'),
        ),
    ]
