# Generated by Django 5.2.11 on 2026-05-17 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_support_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('source', models.CharField(choices=[('BACKEND', 'Backend'), ('BACKEND_CELERY', 'Backend Celery'), ('MOBILE_ANDROID', 'Mobile Android'), ('MOBILE_IOS', 'Mobile iOS')], max_length=32, verbose_name='Manba')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', max_length=16, verbose_name='Jiddiylik')),
                ('kind', models.CharField(choices=[('EXCEPTION', 'Exception'), ('VALIDATION', 'Validation'), ('NETWORK', 'Network'), ('OTHER', 'Other')], default='EXCEPTION', max_length=16, verbose_name='Tur')),
                ('error_type', models.CharField(max_length=255, verbose_name='Xato turi')),
                ('error_message', models.TextField(verbose_name='Xato xabari')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack trace')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name="So'rov yo'li")),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name="So'rov metodi")),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status kodi')),
                ('app_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ilova versiyasi')),
                ('platform', models.CharField(blank=True, max_length=64, null=True, verbose_name='Platforma')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Kontekst')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Barmoq izi')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='Takrorlanish soni')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Birinchi ko'rilgan vaqt")),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Oxirgi ko'rilgan vaqt")),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Xabar yuborilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xato hisoboti',
                'verbose_name_plural': 'Xato hisobotlari',
                'db_table': 'error_reports',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source'], name='error_report_source_idx'), models.Index(fields=['severity'], name='error_report_severity_idx'), models.Index(fields=['kind'], name='error_report_kind_idx'), models.Index(fields=['fingerprint'], name='error_report_fp_idx'), models.Index(fields=['last_seen_at'], name='error_report_last_seen_idx'), models.Index(fields=['user'], name='error_report_user_idx'), models.Index(fields=['is_deleted'], name='error_report_is_del_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('fingerprint',), name='unique_active_error_fingerprint')],
            },
        ),
        migrations.CreateModel(
            name='ValidationErrorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana/vaqt.', verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yangilangan sana/vaqt.', verbose_name='Yangilangan vaqt')),
                ('is_deleted', models.BooleanField(default=False, help_text='Yumshoq o‘chirish holati.', verbose_name='O‘chirilgan')),
                ('error_type', models.CharField(max_length=255, verbose_name='Xato turi')),
                ('request_path', models.CharField(max_length=500, verbose_name="So'rov yo'li")),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Son')),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oyna boshlanishi')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_error_counters', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Validatsiya xato hisoblagichi',
                'verbose_name_plural': 'Validatsiya xato hisoblagichlari',
                'db_table': 'validation_error_counters',
                'indexes': [models.Index(fields=['user'], name='val_err_counter_user_idx'), models.Index(fields=['window_start'], name='val_err_counter_window_idx')],
                'unique_together': {('user', 'error_type', 'request_path')},
            },
        ),
    ]
