# Generated by Django 5.2.11 on 2026-05-18 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_errorreport_validationerrorcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('SOLVED', 'Hal qilindi'), ('USER_UNREACHABLE', 'Foydalanuvchi bilan bog‘lanib bo‘lmadi'), ('DUPLICATE', 'Takroriy murojaat'), ('NOT_RELEVANT', 'Mavzuga aloqasi yo‘q'), ('OTHER', 'Boshqa')], max_length=32, null=True, verbose_name='Yopilish sababi'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='close_reason_note',
            field=models.TextField(blank=True, null=True, verbose_name='Yopilish izohi'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Yopgan admin'),
        ),
    ]
