# Generated by Django 5.2.11 on 2026-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_support_request_close_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Foydalanuvchi hisobi o‘chirilgan sana/vaqt.', null=True, verbose_name='O‘chirilgan vaqt'),
        ),
    ]
