# Generated by Django 5.2.11 on 2026-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='contact_region',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='source',
            field=models.CharField(choices=[('MOBILE_APP', 'Mobile app'), ('LANDING_SITE', 'Landing site'), ('TELEGRAM_BOT', 'Telegram bot'), ('ADMIN', 'Admin'), ('PUBLIC_APP', 'Ilova — ro‘yxatdan o‘tmagan')], default='MOBILE_APP', max_length=32, verbose_name='Manba'),
        ),
    ]
